config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'about', to: 'pages#about'

  get 'courses/new', to: 'courses#new'
  resources :students, except: [:destroy]

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  post 'course_enroll', to: 'enrollments#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
  validates_uniqueness_of :short_name

  has_many :enrollments
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :name, :email

  has_secure_password

  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :require_user

  helper_method :logged_in?, :current_user

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def new
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    unless current_user.courses.include?(course_to_add)
      Enrollment.create(course: course_to_add, student: current_user)
      flash[:notice] = "Now you enrollment in #{course_to_add.name}"
      redirect_to current_user
    else
      flash[:notice] = "Something was wrong with your enrollment"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def new
  end

  def create
    student = Student.find_by(email: params[:sessions][:email].downcase.strip)
    puts params[:sessions][:email].downcase.strip
    puts student
    if student && student.authenticate(params[:sessions][:password])
      flash[:notice] = "You successfully logged in"
      session[:student_id] = student.id
      redirect_to student
    else
      flash[:notice] = "Something wrong with logging info. Check entered email and password"
      redirect_to '/login'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "You successfully logged out"
    redirect_to '/login'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.create(student_params)
    if @student.save
      flash[:success] = "You successfully signed up"
      redirect_to @student
    else
      render 'new'
    end
  end

  def update
    if @student.update(student_params)
      flash[:success] = "Student information was updated successfully."
      redirect_to @student
    else
      render 'edit'
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def require_same_student()
    if current_user != @student
      flash[:notice] = "You can only edit your profile"
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def session_link
    if logged_in?
      link_to 'Log out', logout_path, method: :delete
    else
      link_to 'Login', login_path
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_course.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
      <p><%= course.description %></p>
    </div>
    <div class="card-action">
      <% if logged_in? && !(current_user.courses.include?(course)) %>
        <%= link_to 'Enroll', course_enroll_path(course_id: course.id), method: :post %>
      <% end %>
      <a href="#">Info</a>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="center-align">
      <h3>Courses listing</h3>
    </div>
  </div>
</div>


<div class="row">
  <% @courses.each do |course| %>
    <%= render partial: 'course', locals: {course: course} %>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><%= link_to 'About', about_path, class: "grey-text text-lighten-3" %></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container center">
      © 2022 Tech University
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2" id="fade-out-target">
          <span class="white-text">
            <%= msg %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<ul id="dropdown_pc" class="dropdown-content">
  <% if logged_in? %>
    <li><%= link_to 'Profile', student_path(current_user) %></li>
    <li class="divider"></li>
    <li><%= link_to 'Log out', logout_path, method: :delete  %></li>
    <li class="divider"></li>
    <li><%= link_to 'Add new students', new_student_path %></li>
  <% else %>
    <li><%= link_to 'Login', login_path%></li>
  <% end %>
</ul>

<ul id="dropdown_mobile" class="dropdown-content">
  <% if logged_in? %>
    <li><%= link_to 'Profile', student_path(current_user) %></li>
    <li class="divider"></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    <li class="divider"></li>
    <li><%= link_to 'Add new students', new_student_path %></li>
  <% else %>
    <li><%= link_to 'Login', login_path %></li>
  <% end %>
</ul>

<nav>
  <div class="container nav-wrapper">
    <%= link_to 'Tech University', root_path , {class: "brand-logo right"} %>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Courses', root_path %></li>
      <li><%= link_to 'Students', students_path if logged_in? %></li>
      <li>
        <a class="dropdown-trigger" href="#!" data-target="dropdown_pc">
          Account<i class="material-icons right">arrow_drop_down</i>
        </a>
      </li>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><%= link_to 'Courses', root_path %></li>
  <li><%= link_to 'Students', students_path if logged_in? %></li>
  <li>
    <a class="dropdown-trigger" href="#!" data-target="dropdown_mobile">
      Account<i class="material-icons right">arrow_drop_down</i>
    </a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniverApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav_bar' %>
      <%= render 'layouts/messages' %>
    </header>
    <main>
      <div class="container">
      <%= yield %>
      </div>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_errors.html.erb
<div class="container">
  <div class="row sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel red lighten-2">
        <span class="white-text">
          <strong><%= pluralize(obj.errors.count, "error") %></strong>
          prohibited your profile from being created
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/students/_form.html.erb
<% if @student.errors.any? %>
  <%= render 'shared/errors', obj: @student %>
<% end %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">

        <h3 class="header">
          <%= @student.new_record? ? "Sign Up" : 'Edit profile' %>
        </h3>

        <div class="row">
          <%= form_for(@student, html: { class: "col s12" }) do |f| %>
            <div class="row">
              <div class="input-field col s6">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name, class: 'active' %>
              </div>
              <div class="input-field col s6">
                <%= f.text_field :email, placeholder: "Enter your email", autofocus: true  %>
                <%= f.label :email, class: 'active' %>
              </div>
              <div class="input-field col s6">
                <%= f.password_field :password, placeholder: "Enter your password", autofocus: true  %>
                <%= f.label :password, class: 'active' %>
              </div>
              <div class="input-field col s6">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password", autofocus: true  %>
                <%= f.label :password_confirmation, class: 'active' %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= button_to '', { class: "waves-effect waves-light btn-large" } do %>
                  <% if @student.new_record? %>
                    Sign up <i class="material-icons right">send</i>
                  <% else %>
                    Update data <i class="material-icons right">send</i>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_student.html.erb
<div class="card blue-grey darken-1">
  <div class="card-content white-text">
    <span class="card-title">Name: <%= student.name %></span>
    <p>Email: <%= student.email %></p>
    <p>Course Enrollments: None</p>
  </div>
  <div class="card-action">
    <%= link_to "View profile", student_path(student) %>
    <%= link_to "Edit", edit_student_path(student) if current_user == student %>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="center-align">
      <h3>Students listing</h3>
    </div>
  </div>
</div>


<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <%= render partial: 'student', locals: {student: student} %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row center sign-up-form">
  <div class="col s3 m3">
  </div>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <p>Email: <%= @student.email %></p>
      </div>
      <% if current_user == @student %>
        <div class="card-action">
          <%= link_to 'Edit profile <i class="material-icons right">create</i>'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col s3 m3">
  </div>
</div>

<div class="card-action">
  <h5>Current enrollments</h5>
  <% if @student.courses.empty? %>
    <p>None</p>
  <% else %>
    <div class="row">
      <% @student.courses.each do |course| %>
        <%= render partial: 'courses/course', locals: { course: course } %>
      <% end %>
  <% end %>
  </div>
</div>